spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
  flyway:
    enabled: false

server:
  shutdown: graceful
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "shutdown"
